### ISSUE TITLE
Can't use psycopg2-binary when using a Mac with arm processor

### ISSUE THREAD

**Issue by Joeriksson** [testdrivenio/django-celery-project#10]
Just an FYI. Trying out this course on my MacBook with M1 processor, the Entrypoint script never gets a connection to the db.

It turns out, at least for me, you need to use psycopg2 instead of psycopg2-binary for it to work. Maybe worth mentioning in the course material if other stumble on the same problem?

Also if using psycopg2 on a Macbook Arm, I believe you need the Postgres binaries installed so the package can be built.

**Comment by michael-yin** [comment]
@Joeriksson 

We already add notes to the course and the Github repo README, will close this issue.

Thx.
